### ISSUE TITLE
feat request: sticky provider

### ISSUE THREAD

**Issue by missinglink** [nilsnolde/pelias-qgis-plugin#3]
Hey Nils,

I would love to have a feature which allowed me to select either a 'default provider' or which offered the 'last used' or 'only configured' provider as the top option in the drop-down when searching.

The issue I currently have is that I've set up my credentials for `geocode.earth` (and none yet for OpenRouteService) but then when I go to search it offers me OpenRouteService first, so I have to click the dropdown each time.

It would also be nice if you weren't able to select providers which haven't been properly configured yet, the default workflow after installing is to try and search via OpenRouteService but since it's not configured with credentials so it fails silently and in the console it says:

```
GenericServerError: 401 ({'error': 'Authorization field missing'})
```

Minor UX tweaks, great work on getting it up-and-running, I hope it gains traction in the QGIS community and additional contributors.

**Comment by nilsnolde** [comment]
Thanks @missinglink , good point! Wasn't really happy with that either yet.. Will amend before publishing..

Any news on a Pelias logo btw?

**Comment by missinglink** [comment]
Cool. No news on the logo yet unfortunately, we have a follow up meeting with the designers at the end of next week

**Comment by nilsnolde** [comment]
Alright. Would appreciate if you keep us in the loop there. Would prefer to publish with a proper logo.

Plugin remembers now the last used provider.
