### ISSUE TITLE
Please add a more relevant home page

### ISSUE THREAD

**Issue by pcav** [nilsnolde/pelias-qgis-plugin#5]
It should not be an advertisment of your company, but an informative page about the plugin functionality.
Thanks.

**Comment by nilsnolde** [comment]
Ok understood. Maybe it should be named `helppage` instead. Homepage is a little confusing in that regard. Will amend and re-upload.

**Comment by pcav** [comment]
helpage would be confusing also, because many plugins have an embedded help. anyway, this is a long established convention, and better not change it for now. Thanks for understanding.

**Comment by nilsnolde** [comment]
sure, now that I know it, it won't be happen again either:)
